# Build frontend build
FROM node:13.12.0-alpine

WORKDIR /client

COPY client/package.json .

RUN npm install

RUN npm i -g serve

COPY client/ .

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-s", "dist" ]



FROM python:3.10.12

WORKDIR /ragbackend

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ragbackend/ .

EXPOSE 5000

CMD [ "python3", "-m", "flask", "run", "--host=0.0.0.0" ]